// server.js (фрагмент)

const ROLE_NAMES = [
  "super_admin",
  "admin_main",
  "admin_support",
  "artist",
  "co_artist",
  "producer",
  "beatmaker",
  "sound_engineer",
  "mix_engineer",
  "mastering_engineer",
  "manager",
  "pr_manager",
  "label_rep",
  "designer",
  "video_maker",
  "photographer",
  "friend_close",
  "friend",
  "family",
  "vip_fan_1",
  "vip_fan_2",
  "vip_fan_3",
  "fan_1",
  "fan_2",
  "fan_3",
  "fan_4",
  "fan_5",
  "community_mod_1",
  "community_mod_2",
  "chat_mod_1",
  "chat_mod_2",
  "early_access_1",
  "early_access_2",
  "early_access_3",
  "team_dev",
  "team_design",
  "team_marketing",
  "team_smm",
  "team_content",
  "helper_1",
  "helper_2",
  "helper_3",
  "helper_4",
  "helper_5",
  "partner_1",
  "partner_2",
  "partner_3",
  "partner_4",
  "partner_5",
]; // 50 ролей

const ACCESS_CODES = ROLE_NAMES.map((role, index) => ({
  code: `AVZA-${1000 + index}`, // AVZA-1000 ... AVZA-1049
  role,
  used: false,
}));
